import hijriReference from "./hijriCalendarReference.json";
import { monthName } from "./monthNames";

// The reverse direction of admin/lib/seasonCalendar.ts's own lookup:
// Gregorian -> Hijri instead of Hijri -> Gregorian. seasonCalendar.ts's own
// comment deliberately keeps this direction out of that module ("deriving
// a Hijri year from a Gregorian date... this module must never do") — this
// is that conversion, still reading the same precomputed
// hijriCalendarReference.json (generated by
// tests/generate_hijri_calendar_reference.py from lib/hijri.py) and still
// never computing a Hijri fact itself. CLAUDE.md rule 6: Hijri conversion
// happens in exactly one module; this is a second reader of that module's
// output, not a second one that computes.

interface HijriMonthEntry {
  month: number;
  length: number;
  gregorianStart: string;
}

interface HijriReferenceTable {
  firstYear: number;
  lastSelectableYear: number;
  years: Record<string, HijriMonthEntry[]>;
}

const HIJRI_REFERENCE = hijriReference as HijriReferenceTable;

export interface HijriDate {
  year: number;
  month: number;
  day: number;
}

export class HijriLookupOutOfRangeError extends Error {}

interface MonthStart {
  year: number;
  month: number;
  length: number;
  startMs: number;
}

const MS_PER_DAY = 86_400_000;

// Flattened once at module load, sorted ascending by Gregorian start. The
// generated table is keyed by Hijri year (for the forward direction
// seasonCalendar.ts needs); a reverse lookup needs its own ordering over
// the same entries, by when each Hijri month actually starts in time.
const MONTH_STARTS: MonthStart[] = Object.entries(HIJRI_REFERENCE.years)
  .flatMap(([year, months]) =>
    months.map((entry) => ({
      year: Number(year),
      month: entry.month,
      length: entry.length,
      startMs: Date.parse(`${entry.gregorianStart}T00:00:00Z`),
    }))
  )
  .sort((a, b) => a.startMs - b.startMs);

function toUTCDateOnlyMs(date: Date): number {
  return Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
}

/** Looks up the Hijri calendar date for a Gregorian instant, from the same
 * precomputed table seasonCalendar.ts reads in the other direction.
 *
 * Raises HijriLookupOutOfRangeError if `date` falls outside the years
 * tests/generate_hijri_calendar_reference.py has generated — never computes
 * a fallback, per CLAUDE.md rule 6.
 */
export function toHijriDate(date: Date): HijriDate {
  const targetMs = toUTCDateOnlyMs(date);
  const index = MONTH_STARTS.findLastIndex((entry) => entry.startMs <= targetMs);
  if (index === -1) {
    throw new HijriLookupOutOfRangeError(
      `${date.toISOString().slice(0, 10)} is before the generated Hijri reference table`
    );
  }
  const entry = MONTH_STARTS[index];
  const dayOffset = Math.round((targetMs - entry.startMs) / MS_PER_DAY);
  if (dayOffset >= entry.length) {
    // Only reachable at the very end of the table: every other month's
    // span is bounded by the next generated month's start, which the table
    // is built to have (see generate_hijri_calendar_reference.py's buffer
    // years), so dayOffset never reaches a month's own length except past
    // the last generated month.
    throw new HijriLookupOutOfRangeError(
      `${date.toISOString().slice(0, 10)} is after the generated Hijri reference table`
    );
  }
  return { year: entry.year, month: entry.month, day: dayOffset + 1 };
}

/** "١٧ رمضان ١٤٤٧ هـ" — the exact year/month rendering
 * admin/app/seasons/CalendarPreview.tsx already established (plain digits,
 * monthName("hijri", ...) for the month, "هـ" suffix on the year). */
export function formatHijriDate(hijri: HijriDate): string {
  return `${hijri.day} ${monthName("hijri", hijri.month)} ${hijri.year} هـ`;
}
