import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { HijriLookupOutOfRangeError, formatHijriDate, toHijriDate } from "./hijriLookup";

// Reads tests/hijri_lookup_fixtures.json — generated by
// tests/generate_hijri_lookup_fixtures.py from the real lib/hijri.py, not
// hand-typed here. Same cross-language-ground-truth shape as
// seasonCalendar.conformance.test.ts: if hijriCalendarReference.json is
// ever regenerated with a different range and this reverse lookup drifts
// from what lib/hijri.py actually says, this test catches it.
interface Fixture {
  cases: { gregorian: string; hijri: { year: number; month: number; day: number } }[];
}

const FIXTURES_PATH = new URL("../../tests/hijri_lookup_fixtures.json", import.meta.url);
const fixtures = JSON.parse(readFileSync(FIXTURES_PATH, "utf-8")) as Fixture;

describe("toHijriDate matches lib/hijri.py's to_hijri", () => {
  for (const testCase of fixtures.cases) {
    it(`${testCase.gregorian} -> ${testCase.hijri.year}-${testCase.hijri.month}-${testCase.hijri.day}`, () => {
      const gregorian = new Date(`${testCase.gregorian}T00:00:00Z`);
      expect(toHijriDate(gregorian)).toEqual(testCase.hijri);
    });
  }
});

describe("toHijriDate range guards", () => {
  it("throws for a date before the generated reference table", () => {
    expect(() => toHijriDate(new Date("2000-01-01T00:00:00Z"))).toThrow(
      HijriLookupOutOfRangeError
    );
  });

  it("throws for a date after the generated reference table", () => {
    expect(() => toHijriDate(new Date("2100-01-01T00:00:00Z"))).toThrow(
      HijriLookupOutOfRangeError
    );
  });
});

describe("formatHijriDate", () => {
  it("renders day, Arabic month name, year and the hijri-era suffix", () => {
    expect(formatHijriDate({ year: 1447, month: 10, day: 1 })).toBe("1 شوال 1447 هـ");
  });
});
